apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: n8n-superadmin-binding
subjects:
  - kind: ServiceAccount
    name: n8n-sa
    namespace: automation
roleRef:
  kind: ClusterRole
  name: n8n-superadmin
  apiGroup: rbac.authorization.k8s.io




kubectl apply -f manifests/token/n8n-sa.yaml
kubectl apply -f manifests/token/n8n-role.yaml
kubectl apply -f manifests/token/n8n-rolebinding.yaml
kubectl -n automation create token n8n-sa

# eyJhbGciOiJSUzI1NiIsImtpZCI6IlJzNWl1aHVWeWU0MERudDRBWVA0TWZRYWtXT3BuYjYwRnJ2T2ctUVBiQU0ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1MzE4MjQ2LCJpYXQiOjE3NjUzMTQ2NDYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOWI2ZDNhZTEtN2Y1OS00NjcwLWIyMTktYzFmYTVkYmRkYTQwIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJhdXRvbWF0aW9uIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im44bi1zYSIsInVpZCI6ImVmOGIzZjc3LTM0YTQtNDZiYS1iOTNjLTZlM2MxNmMyNjk0NiJ9fSwibmJmIjoxNzY1MzE0NjQ2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YXV0b21hdGlvbjpuOG4tc2EifQ.s6SO71RlfvLJ4aTYs3LMAWoTPSIvKru2G6zyoGgoR2NQbaN8DYcKRhp5lnn6mUqQc9cYQzpzTW4rT6jqV9aUN_hpePXXNVwqZYYPHzoe05_-L-tDgZ-UKr0RUalfXoVH9qpQW6Ut30aZi5Y5CxtN_p0u9dFM_sWOSnQWrkBYgS2GqKQBON5-CHQT3FiawQ4do5GLhxbyto94_fF3rJ9mD7xMny8K_zniKu7XtJeOquoJt3-IJC-5iLCI64H7cAOvDjNSFYX6CxGoUD5gLLCxngqfvzIH9B4whB-BU4-NzMbymo108BTJcr3-PAEQWdRYJhCNWPGV9xCFE03bgugLKg