falcosidekick:
  enabled: true
  webui:
    enabled: true

  config:
    webhook:
      address: "http://n8n.automation.svc.cluster.local:5678/webhook/falco"
      minimumpriority: "debug"


falco:
  extra:
    env:
      - name: FALCO_K8S_NAMESPACE_DENYLIST
        value: "monitoring"

auditLog:
  enabled: true
  k8sAuditExcludeNamespaces:
    - "monitoring"

