apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quarantine-policy
  namespace: playground
spec:
  podSelector:
    matchLabels:
      security/quarantined: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
