apiVersion: v1
kind: Pod
metadata:
  name: cpu-spike
  namespace: playground
  labels:
    app: cpu-spike
spec:
  containers:
  - name: cpu-spike
    image: busybox
    command: ["sh", "-c", "while true; do :; done"]
