apiVersion: v1
kind: Pod
metadata:
  name: escalate-test
  namespace: playground
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]

# kubectl apply -f escalate-test.yaml
# kubectl exec -n playground escalate-test -- apk add curl
# kubectl exec -n playground escalate-test -- curl google.com

