apiVersion: v1
kind: Pod
metadata:
  name: pod-quarantine-test
  namespace: playground
spec:
  containers:
  - name: shell
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]

# kubectl apply -f pod-quarantine.yaml
# kubectl exec -n playground pod-quarantine-test -it -- sh
