apiVersion: v1
kind: Pod
metadata:
  name: test-busybox
  namespace: playground
  labels:
    app: test-busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 36000"]
