apiVersion: v1
kind: Pod
metadata:
  name: test-shell
  namespace: playground
  labels:
    app: test-shell
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "sleep infinity"]
